name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Replace 'main' with your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.20.121.40.91 }}  # Azure VM host (IP address)
          username: ${{ secrets.aqdam }}  # Azure VM username
          password: ${{ secrets.Servings@123 }}  # Azure VM password
          script: |
            scp -o StrictHostKeyChecking=no -r index.html ${{ secrets.aqdam }}@${{ secrets.20.121.40.91 }}:/var/www/html
