name: Deploying-Webisite-to-Azure-VM

on:
  push:
    branches:
      - main  # Replace 'main' with your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets. }}  # Azure VM host (IP address)
          username: ${{ secrets.}}  # Azure VM username
          password: ${{ secrets.}}  # Azure VM password
          script: |
            sshpass -p ${{ secrets.}} scp -o StrictHostKeyChecking=no -r index.html ${{ secrets. }}@${{ secrets. }}:/var/www/html
